### ISSUE TITLE
Show a list when it matches the first characters only? 

### ISSUE THREAD

**Issue by LightSunChen** [sensen/typing-hero#54]
Hi,

Can you add an option to show a list when it matches the first characters only? 

For example : When typing "he" it will show snippets with keywords "hello", "Hello-ex"... It won't show the ones with keywords "ex-Hello", "myhello"... 
It can avoid random pop-ups when typing.

Thanks

**Comment by sensen** [comment]
I'll make this configurable, but not the default behavior.

**Comment by GitToLife** [comment]
> 
> 
> I'll make this configurable, but not the default behavior.

Please announce after it's available, thanks.

**Comment by sensen** [comment]
@LightSunChen @GitToLife Can you share whether this is something that you'd set once, or something that you'll change every now and then depending on the situation?

**Comment by GitToLife** [comment]
Sorry. What do you mean? BTW I still hope this feature will be available.

**Comment by sensen** [comment]
The list of Snippet Suggestion right now is shown by performing a fuzzy search. This feature will provide an option to change its behavior, so the suggestion only shows as the title of this issue.

What I'm asking is, do you see yourself using those two different search behavior under different situation?

I'm asking because I'm considering where to put this toggle: in the Quick Settings, or in "More Settings".

And yes, I'm planning to work on this in the near future.

**Comment by sensen** [comment]
Published! @LightSunChen @GitToLife

**Comment by GitToLife** [comment]
Hi,

Where is the setting for this feature?

Thanks

**Comment by sensen** [comment]
Update to the latest version, then open the app, tap on the icon on top right to open Quick Settings, then tap on More Settings, then disable `Find matches anywhere in the keyword`.
